server:
  servlet:
    context-path: /vueJsDemo
  port: 8080

# DB Configuration
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/VueJsDemo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#Spring集成Mybatis环境
mybatis:
  #POJO别名扫描包
  type-aliases-package: com.itheima.domain
  #加载Mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml